name: Docker

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set build variables
        run: |
          echo "BUILD_TAG=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          if [[ ${{ github.ref_name }} == *.stable* ]]; then
            echo "BUILD_TYPE=stable" >> "$GITHUB_ENV"
          else
            echo "BUILD_TYPE=latest" >> "$GITHUB_ENV"
          fi

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: assemblyline-service-sample/Dockerfile
          push: ${{ contains(github.ref, 'ref/tags/v') }}
          build-args: |
            version=${{ env.BUILD_TAG }}
            branch=${{ env.BUILD_TYPE }}

          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TYPE }}
