name: Sample

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:

    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: digitelios/assemblyline-services

      - name: Set build variables
        run: |
          echo "BUILD_TAG=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          if [[ ${{ github.ref_name }} == *.stable* ]]; then
            echo "BUILD_TYPE=stable" >> "$GITHUB_ENV"
          else
            echo "BUILD_TYPE=latest" >> "$GITHUB_ENV"
          fi

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: assemblyline-service-sample/Dockerfile
          push: true
          build-args: |
            version=${{ env.BUILD_TAG }}
            branch=${{ env.BUILD_TYPE }}

          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TYPE }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
